/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as ShopOwnerRouteImport } from './routes/shop-owner'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopOwnerIndexRouteImport } from './routes/shop-owner.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as ShopOwnerProductsRouteImport } from './routes/shop-owner.products'
import { Route as ShopOwnerOrdersRouteImport } from './routes/shop-owner.orders'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDeliveryZonesRouteImport } from './routes/admin.delivery-zones'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ShopOwnerShopsIndexRouteImport } from './routes/shop-owner.shops.index'
import { Route as ShopOwnerShopsNewRouteImport } from './routes/shop-owner.shops.new'
import { Route as ShopOwnerOrdersOrderIdRouteImport } from './routes/shop-owner.orders.$orderId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as ShopOwnerShopsShopIdEditRouteImport } from './routes/shop-owner.shops.$shopId.edit'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOwnerRoute = ShopOwnerRouteImport.update({
  id: '/shop-owner',
  path: '/shop-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOwnerIndexRoute = ShopOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopOwnerRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOwnerProductsRoute = ShopOwnerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopOwnerRoute,
} as any)
const ShopOwnerOrdersRoute = ShopOwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopOwnerRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryZonesRoute = AdminDeliveryZonesRouteImport.update({
  id: '/delivery-zones',
  path: '/delivery-zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ShopOwnerShopsIndexRoute = ShopOwnerShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => ShopOwnerRoute,
} as any)
const ShopOwnerShopsNewRoute = ShopOwnerShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => ShopOwnerRoute,
} as any)
const ShopOwnerOrdersOrderIdRoute = ShopOwnerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ShopOwnerOrdersRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const ShopOwnerShopsShopIdEditRoute =
  ShopOwnerShopsShopIdEditRouteImport.update({
    id: '/shops/$shopId/edit',
    path: '/shops/$shopId/edit',
    getParentRoute: () => ShopOwnerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/shop-owner': typeof ShopOwnerRouteWithChildren
  '/vouchers': typeof VouchersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-zones': typeof AdminDeliveryZonesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop-owner/orders': typeof ShopOwnerOrdersRouteWithChildren
  '/shop-owner/products': typeof ShopOwnerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shop-owner/': typeof ShopOwnerIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/shop-owner/orders/$orderId': typeof ShopOwnerOrdersOrderIdRoute
  '/shop-owner/shops/new': typeof ShopOwnerShopsNewRoute
  '/shop-owner/shops/': typeof ShopOwnerShopsIndexRoute
  '/shop-owner/shops/$shopId/edit': typeof ShopOwnerShopsShopIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/vouchers': typeof VouchersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-zones': typeof AdminDeliveryZonesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop-owner/orders': typeof ShopOwnerOrdersRouteWithChildren
  '/shop-owner/products': typeof ShopOwnerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/shop-owner': typeof ShopOwnerIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/shop-owner/orders/$orderId': typeof ShopOwnerOrdersOrderIdRoute
  '/shop-owner/shops/new': typeof ShopOwnerShopsNewRoute
  '/shop-owner/shops': typeof ShopOwnerShopsIndexRoute
  '/shop-owner/shops/$shopId/edit': typeof ShopOwnerShopsShopIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/shop-owner': typeof ShopOwnerRouteWithChildren
  '/vouchers': typeof VouchersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/delivery-zones': typeof AdminDeliveryZonesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/shop-owner/orders': typeof ShopOwnerOrdersRouteWithChildren
  '/shop-owner/products': typeof ShopOwnerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/shop-owner/': typeof ShopOwnerIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/shop-owner/orders/$orderId': typeof ShopOwnerOrdersOrderIdRoute
  '/shop-owner/shops/new': typeof ShopOwnerShopsNewRoute
  '/shop-owner/shops/': typeof ShopOwnerShopsIndexRoute
  '/shop-owner/shops/$shopId/edit': typeof ShopOwnerShopsShopIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/search'
    | '/shop-owner'
    | '/vouchers'
    | '/admin/categories'
    | '/admin/delivery-zones'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/orders/$orderId'
    | '/shop-owner/orders'
    | '/shop-owner/products'
    | '/shops/$shopId'
    | '/admin/'
    | '/orders/'
    | '/shop-owner/'
    | '/admin/orders/$orderId'
    | '/shop-owner/orders/$orderId'
    | '/shop-owner/shops/new'
    | '/shop-owner/shops/'
    | '/shop-owner/shops/$shopId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/search'
    | '/vouchers'
    | '/admin/categories'
    | '/admin/delivery-zones'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/orders/$orderId'
    | '/shop-owner/orders'
    | '/shop-owner/products'
    | '/shops/$shopId'
    | '/admin'
    | '/orders'
    | '/shop-owner'
    | '/admin/orders/$orderId'
    | '/shop-owner/orders/$orderId'
    | '/shop-owner/shops/new'
    | '/shop-owner/shops'
    | '/shop-owner/shops/$shopId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/forbidden'
    | '/login'
    | '/notifications'
    | '/register'
    | '/search'
    | '/shop-owner'
    | '/vouchers'
    | '/admin/categories'
    | '/admin/delivery-zones'
    | '/admin/orders'
    | '/admin/shops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/orders/$orderId'
    | '/shop-owner/orders'
    | '/shop-owner/products'
    | '/shops/$shopId'
    | '/admin/'
    | '/orders/'
    | '/shop-owner/'
    | '/admin/orders/$orderId'
    | '/shop-owner/orders/$orderId'
    | '/shop-owner/shops/new'
    | '/shop-owner/shops/'
    | '/shop-owner/shops/$shopId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  ShopOwnerRoute: typeof ShopOwnerRouteWithChildren
  VouchersRoute: typeof VouchersRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-owner': {
      id: '/shop-owner'
      path: '/shop-owner'
      fullPath: '/shop-owner'
      preLoaderRoute: typeof ShopOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-owner/': {
      id: '/shop-owner/'
      path: '/'
      fullPath: '/shop-owner/'
      preLoaderRoute: typeof ShopOwnerIndexRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-owner/products': {
      id: '/shop-owner/products'
      path: '/products'
      fullPath: '/shop-owner/products'
      preLoaderRoute: typeof ShopOwnerProductsRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
    '/shop-owner/orders': {
      id: '/shop-owner/orders'
      path: '/orders'
      fullPath: '/shop-owner/orders'
      preLoaderRoute: typeof ShopOwnerOrdersRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery-zones': {
      id: '/admin/delivery-zones'
      path: '/delivery-zones'
      fullPath: '/admin/delivery-zones'
      preLoaderRoute: typeof AdminDeliveryZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop-owner/shops/': {
      id: '/shop-owner/shops/'
      path: '/shops'
      fullPath: '/shop-owner/shops/'
      preLoaderRoute: typeof ShopOwnerShopsIndexRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
    '/shop-owner/shops/new': {
      id: '/shop-owner/shops/new'
      path: '/shops/new'
      fullPath: '/shop-owner/shops/new'
      preLoaderRoute: typeof ShopOwnerShopsNewRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
    '/shop-owner/orders/$orderId': {
      id: '/shop-owner/orders/$orderId'
      path: '/$orderId'
      fullPath: '/shop-owner/orders/$orderId'
      preLoaderRoute: typeof ShopOwnerOrdersOrderIdRouteImport
      parentRoute: typeof ShopOwnerOrdersRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/shop-owner/shops/$shopId/edit': {
      id: '/shop-owner/shops/$shopId/edit'
      path: '/shops/$shopId/edit'
      fullPath: '/shop-owner/shops/$shopId/edit'
      preLoaderRoute: typeof ShopOwnerShopsShopIdEditRouteImport
      parentRoute: typeof ShopOwnerRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDeliveryZonesRoute: typeof AdminDeliveryZonesRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminShopsRoute: typeof AdminShopsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDeliveryZonesRoute: AdminDeliveryZonesRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminShopsRoute: AdminShopsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopOwnerOrdersRouteChildren {
  ShopOwnerOrdersOrderIdRoute: typeof ShopOwnerOrdersOrderIdRoute
}

const ShopOwnerOrdersRouteChildren: ShopOwnerOrdersRouteChildren = {
  ShopOwnerOrdersOrderIdRoute: ShopOwnerOrdersOrderIdRoute,
}

const ShopOwnerOrdersRouteWithChildren = ShopOwnerOrdersRoute._addFileChildren(
  ShopOwnerOrdersRouteChildren,
)

interface ShopOwnerRouteChildren {
  ShopOwnerOrdersRoute: typeof ShopOwnerOrdersRouteWithChildren
  ShopOwnerProductsRoute: typeof ShopOwnerProductsRoute
  ShopOwnerIndexRoute: typeof ShopOwnerIndexRoute
  ShopOwnerShopsNewRoute: typeof ShopOwnerShopsNewRoute
  ShopOwnerShopsIndexRoute: typeof ShopOwnerShopsIndexRoute
  ShopOwnerShopsShopIdEditRoute: typeof ShopOwnerShopsShopIdEditRoute
}

const ShopOwnerRouteChildren: ShopOwnerRouteChildren = {
  ShopOwnerOrdersRoute: ShopOwnerOrdersRouteWithChildren,
  ShopOwnerProductsRoute: ShopOwnerProductsRoute,
  ShopOwnerIndexRoute: ShopOwnerIndexRoute,
  ShopOwnerShopsNewRoute: ShopOwnerShopsNewRoute,
  ShopOwnerShopsIndexRoute: ShopOwnerShopsIndexRoute,
  ShopOwnerShopsShopIdEditRoute: ShopOwnerShopsShopIdEditRoute,
}

const ShopOwnerRouteWithChildren = ShopOwnerRoute._addFileChildren(
  ShopOwnerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  ShopOwnerRoute: ShopOwnerRouteWithChildren,
  VouchersRoute: VouchersRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
